<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="10" failed="1" ignored="0" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="1592" started-at="2017-12-01T22:11:11Z" finished-at="2017-12-01T22:11:12Z">
    <groups>
      <group name="TestCase9">
        <method signature="TestingIdentifiers.testCase9()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase9" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase9 -->
      <group name="TestCase8">
        <method signature="TestingIdentifiers.testCase8()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase8" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase8 -->
      <group name="TestCase7">
        <method signature="TestingIdentifiers.testCase7()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase7" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase7 -->
      <group name="TestCase6">
        <method signature="TestingIdentifiers.testCase6()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase6" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase6 -->
      <group name="TestCase5">
        <method signature="TestingIdentifiers.testCase5()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase5" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase5 -->
      <group name="Testcase1">
        <method signature="TestingIdentifiers.testCase1()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase1" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- Testcase1 -->
      <group name="TestCase4">
        <method signature="TestingIdentifiers.testCase4()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase4" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase4 -->
      <group name="TestCase10">
        <method signature="TestingIdentifiers.testCase10()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase10" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase10 -->
      <group name="TestCase3">
        <method signature="TestingIdentifiers.testCase3()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase3" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase3 -->
      <group name="TestCase2">
        <method signature="TestingIdentifiers.testCase2()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase2" class="WAVE_FITS.TestingIdentifiers"/>
      </group> <!-- TestCase2 -->
    </groups>
    <test name="Command line test" duration-ms="1592" started-at="2017-12-01T22:11:11Z" finished-at="2017-12-01T22:11:12Z">
      <class name="WAVE_FITS.TestingIdentifiers">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="openApplication" is-config="true" duration-ms="1422" started-at="2017-12-01T14:11:11Z" finished-at="2017-12-01T14:11:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="loginToApplication()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="loginToApplication" duration-ms="55" started-at="2017-12-01T14:11:12Z" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/openqa/selenium/interactions/internal/Locatable]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.proxyForLocator(DefaultFieldDecorator.java:101)
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.decorate(DefaultFieldDecorator.java:62)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:92)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:79)
	at Pages.AddingEntity.<init>(AddingEntity.java:15)
	at TestResources.PageResources.<init>(PageResources.java:66)
	at WAVE_FITS.Helper.<init>(Helper.java:19)
	at WAVE_FITS.TestingIdentifiers.loginToApplication(TestingIdentifiers.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.internal.Locatable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method status="SKIP" signature="testCase3()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase3" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Scars in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase2" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase3()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase3()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method status="SKIP" signature="testCase1()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase1" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user is unable to write without checking Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.loginToApplication" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase1()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase1()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method status="SKIP" signature="testCase2()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase2" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Tattoos in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase1" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase2()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase2()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="SKIP" signature="testCase6()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase6" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Tracks in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase5" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase6()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase6()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase6 -->
        <test-method status="SKIP" signature="testCase8()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase8" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Mustache in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase7" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase8()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase8()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase8 -->
        <test-method status="SKIP" signature="testCase7()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase7" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Glasses in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase6" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase7()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase7()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase7 -->
        <test-method status="SKIP" signature="testCase5()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase5" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Needle Marks in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase4" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase5()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase5()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase5 -->
        <test-method status="SKIP" signature="testCase4()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase4" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Scars in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase3" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase4()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase4()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase4 -->
        <test-method status="SKIP" signature="testCase9()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase9" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select Beard in Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase8" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase9()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase9()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase9 -->
        <test-method status="SKIP" signature="testCase10()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="testCase10" duration-ms="0" started-at="2017-12-01T14:11:12Z" description="user can select more then two Identifiers" depends-on-methods="WAVE_FITS.TestingIdentifiers.testCase9" finished-at="2017-12-01T14:11:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestingIdentifiers.testCase10()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestingIdentifiers.testCase10()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase10 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:WAVE_FITS.TestingIdentifiers@2a82ee3a]" name="closeBrowser" is-config="true" duration-ms="86" started-at="2017-12-01T14:11:12Z" finished-at="2017-12-01T14:11:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- WAVE_FITS.TestingIdentifiers -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
